document.open();
document.write("<!doctype html>\n");
document.write("<html>\n");
document.write("<head>\n");
document.write("<meta charset=\"utf-8\" />\n");
document.write("<title>View Formatted Source - bookmarklet by skratchdot</title>\n");
document.write("<style type=\"text/css\">\n");
document.write("html, body, h1, div {\n");
document.write("border: 0;\n");
document.write("margin: 0;\n");
document.write("padding: 0;\n");
document.write("}\n");
document.write("body {\n");
document.write("background: #000;\n");
document.write("}\n");
document.write("h1 {\n");
document.write("font-family: Georgia,\"Palatino Linotype\",\"Times New Roman\",serif;\n");
document.write("padding: 10px;\n");
document.write("background: #ddd;\n");
document.write("clear: both;\n");
document.write("float: none;\n");
document.write("}\n");
document.write("a#home {\n");
document.write("color: #000;\n");
document.write("text-decoration: none;\n");
document.write("}\n");
document.write("a#home:hover {\n");
document.write("color: #c80000;\n");
document.write("}\n");
document.write("h1 small {\n");
document.write("font-size: 12px;\n");
document.write("}\n");
document.write("h1 small a {\n");
document.write("color: #c80000;\n");
document.write("text-decoration: none;\n");
document.write("}\n");
document.write("h1 small a:hover {\n");
document.write("text-decoration: underline;\n");
document.write("}\n");
document.write("#copy-container {\n");
document.write("width: 32px;\n");
document.write("height: 32px;\n");
document.write("float: right;\n");
document.write("cursor: pointer;\n");
document.write("position: relative;\n");
document.write("}\n");
document.write("#copy {\n");
document.write("width: 32px;\n");
document.write("height: 32px;\n");
document.write("}\n");
document.write("#editor {\n");
document.write("position: relative;\n");
document.write("}\n");
document.write("</style>\n");
document.write("</head>\n");
document.write("<body>\n");
document.write("<h1 id=\"header\">\n");
document.write("<a id=\"home\" href=\"http://skratchdot.com/projects/domFormat/\">domFormat</a>\n");
document.write("<small>\n");
document.write("bookmarklets:\n");
document.write("<a id=\"fn1\" href=\"javascript:void(0);\">View Source (pretty)</a>\n");
document.write("/\n");
document.write("<a id=\"fn2\" href=\"javascript:void(0);\">View Source (plain)</a>\n");
document.write("/\n");
document.write("<a id=\"fn3\" href=\"javascript:void(0);\">Reload Formatted</a>\n");
document.write("</small>\n");
document.write("<div id=\"copy-container\">\n");
document.write("<img\n");
document.write("id=\"copy\"\n");
document.write("src=\"http://skratchdot.github.com/domFormat/bookmarklet/copy.png\"\n");
document.write("alt=\"Copy formatted source to clipboard\"\n");
document.write("title=\"Copy formatted source to clipboard\"\n");
document.write("/>\n");
document.write("</div>\n");
document.write("</h1>\n");
document.write("<div id=\"editor\">\n");
document.write("Install any of the 3 domFormat bookmarklets by dragging one of the\n");
document.write("red links above to your bookmarks toolbar.  To use the bookmarklets,\n");
document.write("visit any webpage, and click the link that you just saved.\n");
document.write("\n");
document.write("## View Source (pretty) ##\n");
document.write("\n");
document.write("    Displays the formatted HTML of any webpage, in an editor\n");
document.write("    that looks exactly like this webpage. Includes a \"copy\" button\n");
document.write("    in the top right corner that lets you copy all the contents of the\n");
document.write("    editor with one click.\n");
document.write("\n");
document.write("## View Source (plain) ##\n");
document.write("\n");
document.write("    Displays the formatted HTML of any webpage in a &lt;textarea /&gt;.\n");
document.write("\n");
document.write("## Reload Formatted ##\n");
document.write("\n");
document.write("    Takes the formatted HTML of the current page, and reloads the page\n");
document.write("    by using a document.write() statement.\n");
document.write("\n");
document.write("## Credits ##\n");
document.write("\n");
document.write("The following libaries were used in the building of these bookmarklets:\n");
document.write("\n");
document.write("- domFormat: https://github.com/skratchdot/domFormat/\n");
document.write("- CSS Beautify: https://github.com/senchalabs/cssbeautify/\n");
document.write("- JS Beautifier: https://github.com/einars/js-beautify/\n");
document.write("- ACE Editor: https://github.com/ajaxorg/ace/\n");
document.write("</div>\n");
document.write("<script src=\"http://d1n0x3qji82z53.cloudfront.net/src-min-noconflict/ace.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\n");
document.write("<script src=\"http://skratchdot.github.com/domFormat/bookmarklet/ZeroClipboard.min.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\n");
document.write("<script>\n");
document.write("(function () {\n");
document.write("var elem = (document.compatMode === \"CSS1Compat\") ? document.documentElement : document.body,\n");
document.write("height = elem.clientHeight,\n");
document.write("header = document.getElementById('header'),\n");
document.write("editor = document.getElementById('editor'),\n");
document.write("copy = document.getElementById('copy'),\n");
document.write("clip, domString, getBookmarklet, fn1, fn2, fn3;\n");
document.write("\n");
document.write("// Make sure our \"source\" div fills the screen.  ACE editor doesn't allow percentages\n");
document.write("editor.style.height = (height - header.clientHeight) + 'px';\n");
document.write("\n");
document.write("// Now initialize our editor\n");
document.write("window.editor = ace.edit('editor');\n");
document.write("window.editor.setTheme('ace/theme/twilight');\n");
document.write("window.editor.getSession().setMode('ace/mode/html');\n");
document.write("\n");
document.write("// Add functionality to copy button\n");
document.write("ZeroClipboard.setMoviePath('http://skratchdot.github.com/domFormat/bookmarklet/ZeroClipboard.swf');\n");
document.write("clip = new ZeroClipboard.Client();\n");
document.write("clip.setText('');\n");
document.write("clip.glue('copy', 'copy-container');\n");
document.write("clip.addEventListener('onMouseDown', function () {\n");
document.write("clip.setText(window.editor.getValue());\n");
document.write("});\n");
document.write("clip.addEventListener('onComplete', function () {\n");
document.write("alert('The editor contents have been copied to your clipboard.');\n");
document.write("window.editor.focus();\n");
document.write("});\n");
document.write("\n");
document.write("// Populate editor with domFormat string if it exists\n");
document.write("if (window.localStorage) {\n");
document.write("domString = window.localStorage['DOMFORMAT'];\n");
document.write("if (typeof domString === 'string' && domString.length > 0) {\n");
document.write("window.editor.setValue(domString);\n");
document.write("window.editor.clearSelection();\n");
document.write("window.localStorage['DOMFORMAT'] = '';\n");
document.write("}\n");
document.write("}\n");
document.write("\n");
document.write("// Define bookmarklet 1\n");
document.write("fn1 = function (d,w) {\n");
document.write("var doc = d.cloneNode(true) || d,\n");
document.write("s = d.createElement('script');\n");
document.write("s.setAttribute('src', 'http://skratchdot.github.com/domFormat/domFormat.min.js');\n");
document.write("s.addEventListener('load', function() {\n");
document.write("if (w.localStorage) {\n");
document.write("w.localStorage['DOMFORMAT'] = domFormat.getString(doc);\n");
document.write("} else {\n");
document.write("alert('Sorry. This bookmarklet only works on browsers that support localStorage.');\n");
document.write("}\n");
document.write("s = d.createElement('script');\n");
document.write("s.setAttribute('src', 'http://skratchdot.github.com/domFormat/bookmarklet/view-source.js');\n");
document.write("d.body.appendChild(s);\n");
document.write("}, false);\n");
document.write("d.body.appendChild(s);\n");
document.write("};\n");
document.write("\n");
document.write("// Define bookmarklet 2\n");
document.write("fn2 = function (d) {\n");
document.write("var doc = d.cloneNode(true) || d,\n");
document.write("s = d.createElement('script');\n");
document.write("s.setAttribute('src', 'http://skratchdot.github.com/domFormat/domFormat.min.js');\n");
document.write("s.addEventListener('load', function() {\n");
document.write("var ds = domFormat.getString(doc);\n");
document.write("d.open();\n");
document.write("d.write('<textarea wrap=\"off\" id=\"s\" style=\"width:100%;height:100%;border:0;margin:0;padding:0;whitespace:nowrap;\"></textarea>');\n");
document.write("d.getElementById('s').value = ds;\n");
document.write("d.close();\n");
document.write("}, false);\n");
document.write("d.body.appendChild(s);\n");
document.write("};\n");
document.write("\n");
document.write("// Define bookmarklet 3\n");
document.write("fn3 = function (d) {\n");
document.write("var doc = d.cloneNode(true) || d,\n");
document.write("s = d.createElement('script');\n");
document.write("s.setAttribute('src', 'http://skratchdot.github.com/domFormat/domFormat.min.js');\n");
document.write("s.addEventListener('load', function() {\n");
document.write("var ds = domFormat.getString(doc);\n");
document.write("d.open();\n");
document.write("d.write(ds);\n");
document.write("d.close();\n");
document.write("}, false);\n");
document.write("d.body.appendChild(s);\n");
document.write("};\n");
document.write("\n");
document.write("// Helper function for removing whitespace from our bookmarklet code\n");
document.write("getBookmarklet = function (fnText, passWindow) {\n");
document.write("return 'javascript:(' +\n");
document.write("fnText.replace(/\\s+/gi, ' ') +\n");
document.write("'(document' +\n");
document.write("(passWindow === true ? ',window' : '') +\n");
document.write("'));';\n");
document.write("};\n");
document.write("\n");
document.write("// Attach our bookmarklets to our anchor tags\n");
document.write("document.getElementById('fn1').href = getBookmarklet(fn1.toString(), true);\n");
document.write("document.getElementById('fn2').href = getBookmarklet(fn2.toString(), false);\n");
document.write("document.getElementById('fn3').href = getBookmarklet(fn3.toString(), false);\n");
document.write("}());\n");
document.write("</script>\n");
document.write("</body>\n");
document.write("</html>\n");
document.close();
